name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          cd backend
          npm run test
      - name: Install Vercel CLI
        if: success()
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Copy Public and Static Folders
        run: |
          mkdir -p backend/standalone/public
          mkdir -p backend/standalone/.next/static
          cp -r backend/public backend/standalone/public
          cp -r backend/.next/static backend/standalone/.next/static
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy backend/.next/standalone --token=${{ secrets.VERCEL_TOKEN }}
