name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          cd backend
          npm run test
      - name: Install Vercel CLI
        if: success()
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Remove node_modules
        run: |
          ls
          cd backend
          ls
          rm -rf node_modules
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --force --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
