name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - name: Install Python Dependencies
        run: |
          python3.9 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd backend
          source ../.venv/bin/activate
          npm run test
      - name: Install Vercel CLI
        if: success()
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Check Build Size
        run: |
          ls -alh
          cd backend
          ls -alh
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --force --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
